#!/bin/zsh

function d-up() {

  # Start the containers
  docker compose up -d

  # Check the exit status of the previous command
  if [ $? -gt 0 ]; then
    # Retrieve running container details
    compose_output=$(docker compose ls --format json)

    # Extract the name value using `jq` and store in an array
    running_names=($(echo "$compose_output" | jq -r '.[].Name'))

    # Prompt the user for a yes or no input
    echo -e "\nCould not start container because the following containers are already running:"
    printf "\e[31m%s\e[0m\n" "${running_names[@]}"
    echo -n "Do you want to stop them and continue? (y/n): "

    read response

    # Convert the response to lowercase for case-insensitive comparison
    response=$(echo "$response" | tr '[:upper:]' '[:lower:]')

    # Check the user's input and take action accordingly
    if [[ "$response" == "y" || "$response" == "yes" ]]; then
      echo "Stopping the running containers..."
      # Perform desired actions if the response is yes
      for name in $running_names; do
        echo -e "Stopping container: \e[31m$name\e[0m "
        docker compose -p "$name" down

        # Check the exit status of the previous command
        if [ $? -ne 0 ]; then
          echo "Failed to stop container. Exiting..."
          exit 1
        fi
      done

      echo "Starting the container..."
      docker compose up -d
    else
      echo "Aborting. Exiting..."
    fi
  fi

}
