#!/usr/bin/env bash

function g-quick-core() {
    echo -e "Running \e[34m./gradlew \e[32m-x checkstyleMain -x checkstyleTest -x test -p core \e[35m--offline -s\e[0m"
    ./gradlew -x checkstyleMain -x checkstyleTest -x test -p core --offline -s
}
