#!/usr/bin/env bash

function git-clean-branches() {
	echo -e "Cleaning out merged branches... Using \e[34mgit branch \e[31m-d\e[0m"
	git stash && git checkout develop && git pull

	git branch --merged | egrep -v "(^\*|master|main|dev)" | xargs git branch -d
	echo -e "\n\n\e[34mRemaining git branches:\e[0m"
	git branch
	echo "\n\tPulling all local branches..."
	for brname in `git for-each-ref --format='%(refname:short)' refs/heads/`
	do
    	git fetch origin $brname:$brname
	done
}
