#!/usr/bin/env zsh

function git-tag-current() {
	# Get today's date in the desired format (e.g., vYYYY.MM.DD)
	tag_name="v$(date +'%Y.%m.%d')"

	echo -e "Creating tag... Using \"\e[34m$tag_name\e[0m\""
	git tag -a "$tag_name" -m ""
	echo -e "Pushing tag..."
	git push origin "$tag_name"
}
