#!/usr/bin/env zsh

function git-uat-branch-github-description() {

    local SCRIPTFILE="$HOME/.hidden_repo/shortcut-repo/zfuncs/_generate_ticket_links.py"

    echo -e "Running script to create description..."
    python3 "$SCRIPTFILE"

}
