#!/usr/bin/env zsh

function helm-apply-config() {

	if [ -e "helm/helmfile.yaml" ]; then
    	echo -e "Running \e[34mhelmfile \e[32m-f helm/helmfile.yaml -i apply\e[0m"
    	helmfile -f helm/helmfile.yaml -i apply
	else
    	echo -e "\"\e[32mhelm/helmfile.yaml\e[0m\" does \"\e[32mnot exist\e[0m\"\nnothing is done..."
	fi

}
