#!/usr/bin/env zsh

function touch-mkdir() {
    # If no arguments are given, print usage.
    if [[ $# -eq 0 ]]; then
        echo -e "Usage: $0 \e[34m<filepath>...\e[0m"
        return 1
    fi

    # Loop over every argument passed to the function/script.
    for filepath in "$@"; do
        # Extract directory from the file path.
        local dirs="$(dirname "$filepath")"

        echo -e "Creating directories: \e[34m$dirs\e[0m"
        mkdir -p "$dirs"

        echo -e "Touching file:        \e[34m$filepath\e[0m"
        touch "$filepath"
    done
}
